server:
  port: 6061
# myspcloud:
#   item:
#     url: http://127.0.0.1:8081/item/
#mysql
spring:
  application:
    name: app-buyer
  datasource:
    url: jdbc:mysql://localhost:3306/swt_customer?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
# Specify the DBMS
  jpa:
     database: MYSQL
# Show or not log for each sql query
     show-sql: true
    #  generate-ddl: true
# Hibernate ddl auto (create, create-drop, update)
     hibernate:
       ddl-auto: update
       naming: 
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  main:
    allow-bean-definition-overriding: true 